sudo: required
services:
  - docker

before_install:
  - sudo docker build -t kann1bal/docker-react -f ./client/Dockerfile.dev ./client

script:
  - docker run kann1bal/docker-react npm run test -- --coverage

