sudo: required
services:
    - docker
script:
    - sudo docker-compose up --build
    - echo "$Docker_Password" | docker login -u "$Docker_ID" --password-stdin
    - docker push  kann1bal/client
    - docker push  kann1bal/nginx
    - docker push  kann1bal/server
    - docker push  kann1bal/worker
   