sudo: required
services:
  - docker

before_install:
  - sudo docker build -t kann1bal/docker-react -f ./client/Dockerfile.dev ./client

script:
  - docker run kann1bal/docker-react npm run test -- --coverage

after_success:
  - docker build -t kann1bal/client  ./client
  - docker build -t kann1bal/nginx  ./nginx
  - docker build -t kann1bal/server  ./server
  - docker build -t kann1bal/worker  ./worker 
  - echo "$Docker_Password" | docker login -u "$Docker_ID" --password-stdin
  - docker push -t kann1bal/client 
  - docker push -t kann1bal/nginx
  - docker push -t kann1bal/server
  - docker push -t kann1bal/worker