sudo: required
services:
  - docker

before_install:
  - sudo docker build -t kann1bal/docker-react -f ./client/Dockerfile.dev ./client

after_install:
  - docker build -t kann1bal/client  ./client
  - docker build -t kann1bal/nginx  ./nginx
  - docker build -t kann1bal/server  ./server
  - docker build -t kann1bal/worker  ./worker
  
  - echo "$Docker_Password" | docker login -u "$Docker_ID" --password-stdin
  - docker build -t kann1bal/client ./client 
  - docker build -t kann1bal/nginx ./client 
  - docker build -t kann1bal/server ./server  
  - docker build -t kann1bal/worker ./worker 