sudo: required
services:
    - docker
before_install:
    - sudo docker build -t kann1bal/docker-react -f ./client/Dockerfile.dev ./client

after_success:
    - sudo docker-compose up --build
    - echo "$Docker_Password" | docker login -u "$Docker_ID" --password-stdin
    - docker push  kann1bal/client 
    - docker push  kann1bal/nginx
    - docker push  kann1bal/server
    - docker push  kann1bal/worker