version : '3'
services:
     
  postgres:
    image: 'postgres:latest'
  redis:
    image: 'redis:latest'
   
  api:
    image: 'kann1bal/server'
    build:
      dockerfile: Dockerfile
      context: ./server
     
  client:
    image: 'kann1bal/client'
    build:
      dockerfile: Dockerfile
      context: ./client
  
  worker:
    image: 'kann1bal/worker'
    build:
      dockerfile: Dockerfile
      context: ./worker
   
 
  nginx:
    restart: always 
    build: 
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - '3050:80'
  
  

